---
- name: Apply CIS Benchmarks (Hardening)
  hosts: all
  become: true

  vars:
    # --- CORE SETTINGS ---
    rhel9cis_audit_only: true      # Safety first
    setup_audit: true              # Install Audit Tools
    run_audit: true                # Run the scan
    rhel9cis_show_audit_summary: true
    
    # *** KEEP THIS AS JSON (We need the raw data) ***
    rhel9cis_audit_format: json
    
    # --- EXCEPTIONS ---
    rhel9cis_rule_2_1_18: false    # Save Apache
    rhel9cis_set_boot_pass: false
    rhel9cis_skip_filesystem_facts: true
    rhel9cis_ssh_disable_root_login: false
    rhel9cis_sshd_permit_root_login: "yes"
    rhel9cis_authselect_custom_profile_name: "custom_security_profile"
    rhel9cis_firewall_flush: false

  pre_tasks:
    - name: Force audit variable to boolean
      ansible.builtin.set_fact:
        rhel9cis_audit_only: "{{ rhel9cis_audit_only | bool }}"

  roles:
    - role: rhel9_cis

  # --- NEW SECTION: REPORT GENERATOR ---
  post_tasks:
    - name: Find the latest JSON report
      ansible.builtin.shell: "ls -t /opt/*post_scan*.json | head -1"
      register: latest_report
      changed_when: false

    - name: Copy JSON data to Web Server
      ansible.builtin.copy:
        src: "{{ latest_report.stdout }}"
        dest: /var/www/html/cis_data.json
        mode: '0644'
        remote_src: true

    - name: Generate HTML Dashboard
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        mode: '0644'
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>CIS Compliance Dashboard</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <style>
              .pass { color: green; font-weight: bold; }
              .fail { color: red; font-weight: bold; }
              .stats-box { padding: 20px; border-radius: 10px; color: white; text-align: center; }
            </style>
          </head>
          <body class="bg-light">
            <div class="container mt-5">
              <h1 class="mb-4">🛡️ System Compliance Report (CIS RHEL 9)</h1>
              
              <div class="row mb-4">
                <div class="col"><div class="stats-box bg-success"><h3>Pass</h3><h2 id="pass-count">0</h2></div></div>
                <div class="col"><div class="stats-box bg-danger"><h3>Fail</h3><h2 id="fail-count">0</h2></div></div>
                <div class="col"><div class="stats-box bg-primary"><h3>Score</h3><h2 id="score-percent">0%</h2></div></div>
              </div>

              <input type="text" id="search" class="form-control mb-3" placeholder="Search rules..." onkeyup="filterTable()">

              <div class="card shadow">
                <div class="card-body">
                  <table class="table table-hover" id="audit-table">
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>Description</th>
                        <th>Result</th>
                      </tr>
                    </thead>
                    <tbody id="table-body"></tbody>
                  </table>
                </div>
              </div>
            </div>

            <script>
              fetch('cis_data.json')
                .then(response => response.json())
                .then(data => {
                  // The role output structure varies, usually data.results or just data
                  // Adjusting for common Goss output standard
                  let results = data.results || data.tests || []; 
                  
                  let pass = 0, fail = 0;
                  let rows = "";

                  results.forEach(item => {
                    // Check status (Goss uses 'successful', Ansible usually maps to true/false)
                    let isPass = item.successful || item.result === "pass";
                    if (isPass) pass++; else fail++;
                    
                    let statusClass = isPass ? "pass" : "fail";
                    let statusText = isPass ? "PASS" : "FAIL";
                    
                    rows += `<tr>
                      <td>${item.title || item.id || "N/A"}</td>
                      <td>${item.meta?.desc || item.summary || item.desc || "Check Details"}</td>
                      <td class="${statusClass}">${statusText}</td>
                    </tr>`;
                  });

                  document.getElementById('table-body').innerHTML = rows;
                  document.getElementById('pass-count').innerText = pass;
                  document.getElementById('fail-count').innerText = fail;
                  document.getElementById('score-percent').innerText = Math.round((pass / (pass + fail)) * 100) + "%";
                });

              function filterTable() {
                let input = document.getElementById("search").value.toUpperCase();
                let tr = document.getElementById("audit-table").getElementsByTagName("tr");
                for (let i = 1; i < tr.length; i++) {
                  let td = tr[i].textContent || tr[i].innerText;
                  tr[i].style.display = td.toUpperCase().indexOf(input) > -1 ? "" : "none";
                }
              }
            </script>
          </body>
          </html>
