---
- name: Apply CIS Benchmarks (Hardening)
  hosts: all
  become: true

  vars:
    # --- CORE SETTINGS ---
    rhel9cis_audit_only: true      # Safety first
    setup_audit: true              # Install Audit Tools
    run_audit: true                # Run the scan
    rhel9cis_show_audit_summary: true
    
    # *** KEEP THIS AS JSON (We need the raw data) ***
    rhel9cis_audit_format: json
    
    # --- EXCEPTIONS ---
    rhel9cis_rule_2_1_18: false    # Save Apache
    rhel9cis_set_boot_pass: false
    rhel9cis_skip_filesystem_facts: true
    rhel9cis_ssh_disable_root_login: false
    rhel9cis_sshd_permit_root_login: "yes"
    rhel9cis_authselect_custom_profile_name: "custom_security_profile"
    rhel9cis_firewall_flush: false

  pre_tasks:
    - name: Force audit variable to boolean
      ansible.builtin.set_fact:
        rhel9cis_audit_only: "{{ rhel9cis_audit_only | bool }}"

  roles:
    - role: rhel9_cis

  post_tasks:
    # 1. Find the latest report on EVERY host
    - name: Find latest JSON report
      ansible.builtin.shell: "ls -t /opt/*post_scan*.json | head -1"
      register: latest_report_path
      changed_when: false

    # 2. Fetch it to the AWX Controller (Temporary holding area)
    - name: Fetch report to AWX Controller
      ansible.builtin.fetch:
        src: "{{ latest_report_path.stdout }}"
        dest: "/tmp/reports/{{ inventory_hostname }}.json"
        flat: true

    # 3. Push ALL reports to the Web Server (Only runs on the 'client' machine)
    - name: Publish Reports to Web Server
      ansible.builtin.copy:
        src: "/tmp/reports/"
        dest: "/var/www/html/data/"
        mode: '0644'
      delegate_to: client
      run_once: true  # Run this once, copying all fetched files

    # 4. Create the Multi-Host Dashboard
    - name: Generate Master Dashboard
      delegate_to: client
      run_once: true
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        mode: '0644'
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Enterprise Compliance Dashboard</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <style>
              body { background-color: #f8f9fa; }
              .card { margin-bottom: 20px; border: none; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
              .status-pass { color: #198754; font-weight: bold; }
              .status-fail { color: #dc3545; font-weight: bold; }
              .score-box { font-size: 2rem; font-weight: bold; }
            </style>
          </head>
          <body>
            <div class="container py-5">
              <h1 class="mb-4 text-center">🛡️ Infrastructure Compliance Report</h1>

              <div id="server-cards" class="row">
                </div>
            </div>

            <script>
              // List of your servers (Ansible could autogenerate this, but we'll detect dynamically if Apache allows listing,
              // or we just iterate a known list for now).
              const servers = ['client', 'server'];

              const container = document.getElementById('server-cards');

              servers.forEach(hostname => {
                fetch(`data/${hostname}.json`)
                  .then(response => {
                    if (!response.ok) throw new Error("Report not found");
                    return response.json();
                  })
                  .then(data => {
                    // Parse GOSS/CIS Data
                    let results = data.results || data.tests || [];
                    let total = results.length;
                    let failed = results.filter(r => r.result !== "pass" && !r.successful).length;
                    let passed = total - failed;
                    let score = Math.round((passed / total) * 100);
                    let color = score > 90 ? "success" : (score > 70 ? "warning" : "danger");

                    let html = `
                      <div class="col-md-6">
                        <div class="card">
                          <div class="card-header bg-${color} text-white">
                            <h4 class="m-0">${hostname.toUpperCase()}</h4>
                          </div>
                          <div class="card-body text-center">
                            <div class="row">
                              <div class="col">
                                <div class="text-muted">Score</div>
                                <div class="score-box text-${color}">${score}%</div>
                              </div>
                              <div class="col">
                                <div class="text-muted">Passed</div>
                                <h3 class="text-success">${passed}</h3>
                              </div>
                              <div class="col">
                                <div class="text-muted">Failed</div>
                                <h3 class="text-danger">${failed}</h3>
                              </div>
                            </div>
                            <hr>
                            <button class="btn btn-outline-primary btn-sm" onclick="toggleDetails('${hostname}')">View Failures</button>
                            <div id="details-${hostname}" class="mt-3 text-start" style="display:none; max-height:300px; overflow-y:auto;">
                              <small>
                                ${results.filter(r => r.result !== "pass" && !r.successful).map(r =>
                                  `<div class="text-danger border-bottom py-1">❌ ${r.title || r.desc}</div>`
                                ).join('')}
                              </small>
                            </div>
                          </div>
                        </div>
                      </div>
                    `;
                    container.innerHTML += html;
                  })
                  .catch(err => console.error(`Could not load ${hostname}:`, err));
              });

              function toggleDetails(id) {
                let el = document.getElementById('details-' + id);
                el.style.display = el.style.display === 'none' ? 'block' : 'none';
              }
            </script>
          </body>
          </html>
