---
- name: Apply CIS Benchmarks (Hardening)
  hosts: all
  become: true
  roles:
    - role: rhel9_cis
      vars:
        rhel9cis_level: 2
        rhel9cis_allow_reboot: false
        rhel9cis_audit_only: true 
        rhel9cis_set_boot_pass: false
        setup_audit: true
        run_audit: true
        audit_format: json
        audit_conf_dir: /tmp
