---
- name: Setup Web Server on RHEL
  hosts: all
  become: true  # This means "sudo"
  tasks:
    - name: Install Apache (httpd)
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and Enable Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Create a custom Index Page
      ansible.builtin.copy:
        content: "<h1>Hello from AWX! This server was built by automation.</h1>"
        dest: /var/www/html/index.html

    - name: Allow HTTP through Firewall
      ansible.builtin.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
